services:
  mysql:
    image: mysql:8.0
    container_name: reposteria_db
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: reposteria
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - reposteria_network

volumes:
  mysql_data:

networks:
  reposteria_network:
    driver: bridge